### ISSUE TITLE
Wrong GND connection to Raspberry Pi 

### ISSUE THREAD

**Issue by Leodom01** [ryanlopezzzz/EEG#12]
![image](https://user-images.githubusercontent.com/25131781/150672798-337143e5-363e-4e52-b0d6-be5d3fdc00d2.png)
As you can see the second pin from top, in the right row is dedicated to 5V power, while the third one is for ground.

![image](https://user-images.githubusercontent.com/25131781/150672832-bbdd1f47-8a4d-415e-a02a-6b16bdddb4cb.png)
 
Here you set the ground connection in the 5V power out of the Raspberry, you should move the black line to the following pin.

I hope I'm right, thank you for your great project and the awesome description you did a great job and I'm spending some great time with it trying to replicate it! :)

**Comment by ruining99** [comment]
Thanks for pointing out this issue! I just fixed the image.
Glad to hear you are having fun with this project. Best of luck!!
